### ISSUE TITLE
HAL: error

### ISSUE THREAD

**Issue by Mehdidadash** [rodw-au/linuxcnc-cia402#1]
hi.
i have this error:
HAL: ERROR: pin 'lcec.0.3.out-01' not found
`mehdi@2C-44-FD-0E-B1-03:~/linuxcnc/configs/linuxcnc-cia402$ linuxcnc cia402.ini
LINUXCNC - 2.10.0-pre0-173-gcadd89a54
Machine configuration directory is '/home/mehdi/linuxcnc/configs/linuxcnc-cia402'
Machine configuration file is 'cia402.ini'
Starting LinuxCNC...
emc/iotask/ioControl_v2.cc 888: iov2: can't load tool table.
linuxcnc TPMOD=tpmod HOMEMOD=homemod EMCMOT=motmod
Note: Using POSIX realtime
Found file(REL): ./cia402.hal
Failed to register PDO entry: No such file or directory
LCEC: master 0 PDO entry registration failed
lcec: rtapi_app_main: Invalid argument (-22)
./cia402.hal:15: waitpid failed /usr/bin/rtapi_app lcec
./cia402.hal:15: /usr/bin/rtapi_app exited without becoming ready
./cia402.hal:15: insmod for lcec failed, returned -1
Shutting down and cleaning up LinuxCNC...
Running HAL shutdown script
HAL: ERROR: pin 'lcec.0.3.out-01' not found
shutdown.hal:2: unlink failed
iov2: exiting
Note: Using POSIX realtime
LinuxCNC terminated with an error.  You can find more information in the log:
    /home/mehdi/linuxcnc_debug.txt
and
    /home/mehdi/linuxcnc_print.txt
as well as in the output of the shell command 'dmesg' and in the terminal
`

i installed linuxcnc using iso and upgraded it to 2.9 using buildbot. i used instructions in the Ethercat Installation instructions.txt and your post in forum.linuxcnc.org .
i issued this error here because for some unknown reasons forum is blocking me to enter but i can use other subdomains like wiki.linuxcnc.org !!

**Comment by rodw-au** [comment]
Most likely its becasue you are using the XML here is for my drives and your devices. You need to edit or remove devices to suit what  you have connected.
You probably do not have a I/O module attached to your BUS,
