### ISSUE TITLE
lcec failture

### ISSUE THREAD

**Issue by wujianya** [rodw-au/linuxcnc-cia402#3]
Hello, I based on xenomai+linuxcnc+igh, the test found that when executing 1.halrun 2.loadusr -w lcec_conf./*.xml 3,loadrt lcec, the following error will be reported when executing the third step call bus ecrt_* function is not defined: I also noticed that the EtherCAT0 application appeared in /dev/EtherCAT0, and also appeared in /dev/rtdm/EtherCAT0.

**Comment by rodw-au** [comment]
This is not related to cia402 so I can't really help here.
The location of the ethercat modules depends on how you install it (eg from source or from the igh repository)
The installation process is well documented on the linuxcnc forum in sticky posts.
Please redirect your questions there.
